name: frame_audio_clip
description: "Record streamed audio clips from the Brilliant Labs Frame into a list for review and playback"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.33.4
  logging: ^1.2.0
  raw_sound:
    git: https://github.com/HintAzuma/flutter_raw_sound
  simple_frame_app: ^0.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
  - packages/simple_frame_app/lua/battery.min.lua
  - packages/simple_frame_app/lua/data.min.lua
  - packages/simple_frame_app/lua/code.min.lua
  - packages/simple_frame_app/lua/plain_text.min.lua
  - assets/frame_app.lua
