name: frame_audio_clip
description: "Record streamed audio clips from the Brilliant Labs Frame into a list for review and playback"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  frame_msg: ^2.0.0
  logging: ^1.2.0
  raw_sound:
    git: https://github.com/HintAzuma/flutter_raw_sound
  share_plus: ^10.1.0
  simple_frame_app: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
  - packages/frame_msg/lua/battery.min.lua
  - packages/frame_msg/lua/data.min.lua
  - packages/frame_msg/lua/code.min.lua
  - packages/frame_msg/lua/plain_text.min.lua
  - assets/frame_app.lua
